"use client";
import Head from 'next/head';
import React, { useEffect } from "react";
import Link from "next/link";
import { supabase } from "./lib/supabase";
import Image from 'next/image';
import { useRouter } from 'next/navigation'; // Updated: Correct hook for navigation

export default function Home() {
  const router = useRouter(); // Use the Next.js router

  const getSession = async () => {
    const {
      data: { session },
    } = await supabase.auth.getSession();
    console.log(session);
    if (session) {
      console.log("User already logged in. Redirecting to dashboard.");
      router.push("/dashboard");
    }
  };

  useEffect(() => {
    getSession();
  }, []); // Fetch session on page load

  const login = async () => {
    try {
      // Initiate OAuth login
      const { error } = await supabase.auth.signInWithOAuth({
        provider: "spotify",
        options: {
          redirectTo: "http://localhost:3000/dashboard",
          scopes: 'playlist-modify-public playlist-modify-private',
        },
      });

      if (error) {
        console.error("Error initiating login:", error.message);
        return;
      }

      // Listen to the auth state change
      supabase.auth.onAuthStateChange(async (event, session) => {
        if (event === 'SIGNED_IN' && session) {
          console.log("User logged in:", session.user);

          // Sync the user's profile with Supabase
          await syncUserProfile(session.user);

          // Redirect to dashboard after successful login
          router.push("/dashboard");
        }
      });
    } catch (error) {
      console.log("Error logging in:", error);
    }
  };

  // Function to sync the user profile
 // Function to sync the user profile
const syncUserProfile = async (user) => {
  console.log("Attempting to sync user profile:", user); // Debug statement

  const { id, email, user_metadata } = user;
  try {
    // Check if the profile already exists
    const { data: existingProfile, error: selectError } = await supabase
      .from('profiles')
      .select('*')
      .eq('id', id)
      .single();

    if (selectError) {
      console.error("Error checking for existing profile:", selectError);
    }

    // If the profile doesn't exist, insert it
    if (!existingProfile) {
      const { error: insertError } = await supabase.from('profiles').insert([
        {
          id,
          email,
          display_name: user_metadata.full_name || user_metadata.name || "Unknown User",
          spotify_id: user_metadata.spotify_id || user_metadata.sub,
          avatar_url: user_metadata.avatar_url || "",
        },
      ]);

      if (insertError) {
        console.error('Error inserting profile:', insertError);
      } else {
        console.log("Profile successfully inserted");
      }
    } else {
      console.log("Profile already exists:", existingProfile);
    }
  } catch (error) {
    console.error("Error syncing user profile:", error);
  }
};


  return (
    <html data-theme="luxury">
      <body>
        <Head>
          <title>BLND</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="min-h-screen">
          <header>
            <div className="container mx-auto px-4 py-6">
              <h1 className="text-3xl font-bold" style={{ fontFamily: 'Planet Kosmos' }}>blnd</h1>
            </div>
          </header>

          <section className="container mx-auto px-4 py-12">
            <div className="text-center">
              <h2 className="text-4xl font-bold mb-4">Blend Your Music with Friends Seamlessly</h2>
              <p className="text-lg">BLND utilizes Spotify & LastFM to mash playlists to create a diversified experience!</p>
              <div className="flex justify-center space-x-4 mb-8">
                <button className="btn btn-primary" onClick={login}>Login</button>
                <Link href="/signup">
                  <button className="btn btn-secondary">Signup</button>
                </Link>
              </div>
              <Image src="/public/sp1.svg" alt="Hero Image" width={1000} height={1000} />
            </div>
          </section>

          <footer>
            <div className="container mx-auto px-4 py-6">
              <p className="text-center">© 2024 My Landing Page. All rights reserved.</p>
            </div>
          </footer>
        </main>
      </body>
    </html>
  );
}
