"use client";
import Head from 'next/head';
import React, { useEffect } from "react";
import Link from "next/link";
import { supabase } from "./lib/supabase";
import Image from 'next/image';
import { useRouter } from 'next/navigation'; // Updated: Correct hook for navigation

export default function Home() {
  const router = useRouter(); // Use the Next.js router

  const getSession = async () => {
    const {
      data: { session },
    } = await supabase.auth.getSession();
    console.log(session);
    if (session) {
      console.log("User already logged in. Redirecting to dashboard.");
      router.push("/dashboard");
    }
  };

  useEffect(() => {
    getSession();
  }, []); // Fetch session on page load

  const login = async () => {
    try {
      // Initiate OAuth login
      const { error } = await supabase.auth.signInWithOAuth({
        provider: "spotify",
        options: {
          redirectTo: "http://localhost:3000/dashboard",
        },
      });

      if (error) {
        console.error("Error initiating login:", error.message);
        return;
      }

      // Listen to the auth state change
      supabase.auth.onAuthStateChange(async (event, session) => {
        if (event === 'SIGNED_IN' && session) {
          console.log("User logged in:", session.user);

          // Redirect to dashboard after successful login
          router.push("/dashboard");
        }
      });
    } catch (error) {
      console.log("Error logging in:", error);
    }
  };

  return (
    <html data-theme="luxury">
      <body>
        <Head>
          <title>BLND</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="min-h-screen">
          <header>
            <div className="container mx-auto px-4 py-6">
              <h1 className="text-3xl font-bold" style={{ fontFamily: 'Planet Kosmos' }}>blnd</h1>
            </div>
          </header>

          <section className="container mx-auto px-4 py-12">
            <div className="text-center">
              <h2 className="text-4xl font-bold mb-4">Blend Your Music with Friends Seamlessly</h2>
              <p className="text-lg">BLND utilizes Spotify & LastFM to mash playlists to create a diversified experience!</p>
              <div className="flex justify-center space-x-4 mb-8">
                <button className="btn btn-primary" onClick={login}>Login</button>
                <Link href="/signup">
                  <button className="btn btn-secondary">Signup</button>
                </Link>
              </div>
              <Image src="/public/sp1.svg" alt="Hero Image" width={1000} height={1000} />
            </div>
          </section>

          <footer>
            <div className="container mx-auto px-4 py-6">
              <p className="text-center">© 2024 My Landing Page. All rights reserved.</p>
            </div>
          </footer>
        </main>
      </body>
    </html>
  );
}
